### ISSUE TITLE
Database file

### ISSUE THREAD

**Issue by demianrey** [pingProMax/gov2panel#1]
Hello, where is the database file located?

**Comment by pingProMax** [comment]
https://github.com/pingProMax/gov2panel/releases/tag/gov2panel
[gov2panel.sql](https://github.com/pingProMax/gov2panel/releases/download/gov2panel/gov2panel.sql)

**Comment by demianrey** [comment]
Sorry, I hadn't seen the release files, I manually compiled the tree files and there I was looking for the database haha
The panel looks great and doesn't require as much to run as other panels.
Thanks and regards
