### ISSUE TITLE
订阅选叠加后无法购买

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#10]
1.当订阅 套的类型为叠加 前台用户无法直接购买此订阅
2.后台修改用户订阅权限下拉列表里也看不到类型为叠加的订阅
订阅类型 改覆盖后1 问题解决，且可以直接续费，2问题依旧

**Comment by pingProMax** [comment]
> 改用户订阅权限下拉列

嘗試執行
update.sql

**Comment by wukong1122** [comment]
sql是下的最小的 新安装的所有没使用update那个sql

**Comment by wukong1122** [comment]
> 1.当订阅 套的类型为叠加 前台用户无法直接购买此订阅 2.后台修改用户订阅权限下拉列表里也看不到类型为叠加的订阅 订阅类型 改覆盖后1 问题解决，且可以直接续费，2问题依旧

纠正一下：当第订阅类型改覆盖，用户购买订阅后，再改回叠加，可以直接续费，但是2问题依旧

**Comment by pingProMax** [comment]
> 2.后台修改用户订阅权限下拉列表里也看不到类型为叠加的订阅

這裡可能需要解析一下，疊加的套餐是這樣的，僅疊加流量和時間，用戶的訂閱組不會更改，在添加節點時也不可設定疊加的套餐

**Comment by wukong1122** [comment]
我的理解可能有偏差:叠加套餐是月付类型为主.比如我订购这个套餐第一个月,没用完耶没到期,我可以提前下单套餐会顺延,不会在我新购买订阅的这天重置流量.
现在问题是如果选叠加就不能完成初次的订阅购买

**Comment by pingProMax** [comment]
> 题是如果选叠加就不能完成初次的订阅购买

是的，確實有這樣的問題。兩個方案，一、如果用戶沒有訂閱權限，不允許購買疊加類型的套餐；二、像覆蓋類型的套餐一樣，也是一個訂閱權限組，不同的是可以疊加；或者你有更好的建議，

**Comment by wukong1122** [comment]
我的想法建议：
1.覆盖类型套餐：所有用户都有初次订阅权限，主要用于一次性流量不限时（或者365天内）套餐，不管用户流量用完没用完，在再次购买时清空之前流量获取新购套餐流量。一般用户都会在用完或者接近用完时订购新套餐
2.叠加类型套餐：所有用户都有初次订阅权限，主要用于周期性月付类型套餐，要几个月可以一次购买叠加，每月流量固定，叠加的是时长。如果用户没有续订订阅过期，到期后（或者再次续订时）将之前套餐流量清0

**Comment by pingProMax** [comment]
> 我的想法建议： 1.覆盖类型套餐：所有用户都有初次订阅权限，主要用于一次性流量不限时（或者365天内）套餐，不管用户流量用完没用完，在再次购买时清空之前流量获取新购套餐流量。一般用户都会在用完或者接近用完时订购新套餐 2.叠加类型套餐：所有用户都有初次订阅权限，主要用于周期性月付类型套餐，要几个月可以一次购买叠加，每月流量固定，叠加的是时长。如果用户没有续订订阅过期，到期后（或者再次续订时）将之前套餐流量清0

@MargaretCohen2000
註冊兩個帳號全消失了，我直接買了一個帳號
