### ISSUE TITLE
节点状态显示不正确

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#11]
后端：xrayr 
协议：vemss+tls。 Trojan

当xrayr日志中无在线活跃用户时，前端节点状态显示为异常，实际节点是同的只是没有上报用户，当你在客户端测速一次建立一个连接后，前端节点状态中即显示正常。已活跃用户判断节点状态好像不太合理

**Comment by pingProMax** [comment]
> 后端：xrayr 协议：vemss+tls。 Trojan
> 
> 当xrayr日志中无在线活跃用户时，前端节点状态显示为异常，实际节点是同的只是没有上报用户，当你在客户端测速一次建立一个连接后，前端节点状态中即显示正常。已活跃用户判断节点状态好像不太合理

目前是用，用戶上報來判斷節點在線狀態， 確實比較不好；暫定改為-節點獲取用戶資料的動作來判斷節點在線狀態（待更改）

**Comment by pingProMax** [comment]
> 后端：xrayr 协议：vemss+tls。 Trojan
> 
> 当xrayr日志中无在线活跃用户时，前端节点状态显示为异常，实际节点是同的只是没有上报用户，当你在客户端测速一次建立一个连接后，前端节点状态中即显示正常。已活跃用户判断节点状态好像不太合理

判斷節點狀態功能修改完成，需要重新下載gov2panel，重啟項目，並且更新部分前端資源

**Comment by wukong1122** [comment]
👍👍👍

**Comment by wukong1122** [comment]
节点没有在线的用户连接的话正常应该显示0用户，现在显示的是undefined

**Comment by pingProMax** [comment]
> 节点没有在线的用户连接的话正常应该显示0用户，现在显示的是undefined

ok
https://github.com/pingProMax/gov2panel/commit/1cd4065b00a59cfed1e730e1c3e1f3afd0659bc9
