### ISSUE TITLE
钱包无法充值成功

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#12]
易支付接口 
点充值。扣款成功后正常回调后 用户中心余额未增加 且充值消费记录里没有充值的订单信息

**Comment by pingProMax** [comment]
> 易支付接口 点充值。扣款成功后正常回调后 用户中心余额未增加 且充值消费记录里没有充值的订单信息

易支付這邊已經測試過，可能你用的易支付魔改了？

**Comment by wukong1122** [comment]
呃··我用的是自己搭建的彩虹易支付 一直在v2board 和发卡站上用正常
现在它的问题是 能支付成功 只是系统内并没正常回调并跳转到准确页面  
跳转到还是前往易支付页面前的提交页 而不是用户首页 且订单交易数据并未被更新
系统是好系统速度非常ok 目前很多功能和配置已经跑通了
如果后续做doc需要我协助 可以叫我

**Comment by pingProMax** [comment]
> 呃··我用的是自己搭建的彩虹易支付 一直在v2board 和发卡站上用正常 现在它的问题是 能支付成功 只是系统内并没正常回调并跳转到准确页面 跳转到还是前往易支付页面前的提交页 而不是用户首页 且订单交易数据并未被更新 系统是好系统速度非常ok 目前很多功能和配置已经跑通了 如果后续做doc需要我协助 可以叫我

能搭建個測試用的易支付嗎？測試用，我這邊看看

**Comment by wukong1122** [comment]
你可以直接用我这边搭建你 你看你需要什么信息我提供给你  服务root 和易支付后台?

**Comment by pingProMax** [comment]
> 你可以直接用我这边搭建你 你看你需要什么信息我提供给你 服务root 和易支付后台?

易支付后台

**Comment by wukong1122** [comment]
tg 加你

**Comment by wukong1122** [comment]
@kkyykkyyy

**Comment by wukong1122** [comment]
留一个邮箱或者其他方式我讲易支付后台信息发你

**Comment by pingProMax** [comment]
> 留一个邮箱或者其他方式我讲易支付后台信息发你

我的tg被限制雙向了
@pingProMax

**Comment by pingProMax** [comment]
> 呃··我用的是自己搭建的彩虹易支付 一直在v2board 和发卡站上用正常 现在它的问题是 能支付成功 只是系统内并没正常回调并跳转到准确页面 跳转到还是前往易支付页面前的提交页 而不是用户首页 且订单交易数据并未被更新 系统是好系统速度非常ok 目前很多功能和配置已经跑通了 如果后续做doc需要我协助 可以叫我


註冊的帳號今天不知道為何自己消失了，重新註冊了
tg  @ColoredTree
