### ISSUE TITLE
优惠券 指定订阅无效

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#13]
优惠券 指定订阅 下拉选择订阅套餐保存后  再次进来编辑依旧显示空
好像并未提交到数据库

**Comment by pingProMax** [comment]
> 优惠券 指定订阅 下拉选择订阅套餐保存后 再次进来编辑依旧显示空 好像并未提交到数据库

確實是，感謝測試

**Comment by pingProMax** [comment]
> > 优惠券 指定订阅 下拉选择订阅套餐保存后 再次进来编辑依旧显示空 好像并未提交到数据库
> 
> 確實是，感謝測試

已經修復，是模板問題，關鍵字多了個s
https://github.com/pingProMax/gov2panel/commit/7fba51a08e8edea70a89249f3ade822bdf026ca8

**Comment by wukong1122** [comment]
ok  有个gov2panel的tg群是官方的么

**Comment by pingProMax** [comment]
> ok 有个gov2panel的tg群是官方的么

沒有，你可以建造一個
