### ISSUE TITLE
节点名称插入emoj 图标会报错

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#14]
节点标题如果含国旗emo图标无法提交会报数据库错误，编码问题？
节点名称带个图标比较直观一点，可以的话建议修复一下

**Comment by wukong1122** [comment]
当我将图标直接写入数据库后 网页后台中无法正确识别 显示两个？？

**Comment by wukong1122** [comment]
当我通过数据库插入新的 节点数据时，网站后台并没有将新的节点显示出来，show 参数是1 
请问是有关联表没更新还是，因为缓存

**Comment by pingProMax** [comment]
> 台中无法正

charset=utf8 改成 charset=utf8mb4 即可

**Comment by wukong1122** [comment]
我这边测试好像并不行哦 问题依旧一样

**Comment by pingProMax** [comment]
> 我这边测试好像并不行哦 问题依旧一样

需要重啟項目
