### ISSUE TITLE
希望增加一个快速复制节点功能

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#15]
直接快速复制节点，然后修改几个参数即可设置出一个新节点

**Comment by pingProMax** [comment]
> 直接快速复制节点，然后修改几个参数即可设置出一个新节点

待辦的工作

**Comment by pingProMax** [comment]
> 直接快速复制节点，然后修改几个参数即可设置出一个新节点

功能實現
https://github.com/pingProMax/gov2panel/commit/4b63efec44dfa3fce15453572b495f084c1bcba0

**Comment by wukong1122** [comment]
👍👍
