### ISSUE TITLE
当订阅标题里出现空格 订阅会被隐藏

### ISSUE THREAD

**Issue by wukong1122** [pingProMax/gov2panel#16]
当订阅标题里任意位置出现空格 用户更新订阅后此节点在用户客户端会被隐藏无法显示出来

**Comment by pingProMax** [comment]
> 订阅标题

這邊測試沒有這樣的問題，或許是你設定的節點顯示狀態為隱藏？

**Comment by wukong1122** [comment]
不是 说错了，不是标题里，是节点地址里如果失误输入了空格无论在前面后面还是中间 就会触发

**Comment by pingProMax** [comment]
![image](https://github.com/pingProMax/gov2panel/assets/44503794/dcbf68e8-675c-4704-b4b1-538a9b6c9c64)

**Comment by pingProMax** [comment]
> 不是 说错了，不是标题里，是节点地址里如果失误输入了空格无论在前面后面还是中间 就会触发

https://github.com/pingProMax/gov2panel/commit/1c18adb597bf939ed925b11d180bd71b4249b2b6
