### ISSUE TITLE
修改密码功能有bug

### ISSUE THREAD

**Issue by xiya233** [pingProMax/gov2panel#2]
你好，开发者

使用默认的管理员账号密码adminx/123456789登录后，在面板里面修改新密码后不能登录，提示密码错误...

**Comment by pingProMax** [comment]
https://github.com/pingProMax/gov2panel/commit/9ea6ded0ee34d4dcfd5b5a1596d7babe83fee413

你好，再设计之初没考虑md5密码加盐，此处忘记更新盐了
已经修复并编译和测试，，重新下载“gov2panel” 运行即可。
老密码不知道如何登入，
手动修改数据库v2_user表，password 字段：6639b10c5cbcd478da4010d97a3c74de，password_salt字段：ebfbb20e  即可恢复密码

**Comment by xiya233** [comment]
> [9ea6ded](https://github.com/pingProMax/gov2panel/commit/9ea6ded0ee34d4dcfd5b5a1596d7babe83fee413)
> 
> 你好，在设计之初没考虑到md5密码加盐，此处忘记更新盐了 已经修复并编译和测试，，重新下载“gov2panel” 运行即可。 老密码不知道如何登入，请进行下面操作 手动修改数据库v2_user表，password 字段：6639b10c5cbcd478da4010d97a3c74de，password_salt字段：ebfbb20e 即可恢复密码

ok，已经好了，谢谢。
