### ISSUE TITLE
添加节点时出现问题，Panel Start fialed: server port must > 0

### ISSUE THREAD

**Issue by daibva** [pingProMax/gov2panel#4]
xraryr报错
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: XrayR 0.9.1 (A Xray backend that supports many panels)
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: 2023/10/25 19:05:42 Start the panel..
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: 2023/10/25 19:05:42 Xray Core Version: 1.8.4
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: 2023/10/25 19:05:42 [Warning] core: Xray 1.8.4 started
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: 2023/10/25 19:05:42 Panel Start fialed: server port must > 0
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: panic: Panel Start fialed: server port must > 0
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: goroutine 1 [running]:
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: log.Panicf({0x358c09d?, 0x39d0520?}, {0xc0006e9e20?, 0xc0006ff3b0?, 0x2dd6ea0?})
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]:         log/log.go:439 +0x65
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00017f4c0)
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]:         github.com/XrayR-project/XrayR/panel/panel.go:210 +0x5db
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]: main.main()
Oct 25 19:05:42 racknerd-7043e5 XrayR[68378]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Oct 25 19:05:42 racknerd-7043e5 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 25 19:05:42 racknerd-7043e5 systemd[1]: XrayR.service: Failed with result 'exit-code'.
^C

**Comment by pingProMax** [comment]
节点的数据贴上来

**Comment by daibva** [comment]
Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 32 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "GoV2Panel" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel
    ApiConfig:
      ApiHost: "http://172.93.189.155"
      ApiKey: "123456"
      NodeID: 6
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 30 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
      DisableCustomConfig: false # disable custom config for sspanel
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      DisableLocalREALITYConfig: false  # disable local reality config
      EnableREALITY: false # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: cdn66.uzs.cc:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - cdn66.uzs.cc
        PrivateKey: YOUR_PRIVATE_KEY # Required, execute './xray x25519' to generate.
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
          - ""
          - 0123456789abcdef
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "cdn66.uzs.cc" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by pingProMax** [comment]
指的是 网站后台，节点管理 - 编辑 - 数据栏中的数据

**Comment by daibva** [comment]
数据栏没填任何数据

**Comment by pingProMax** [comment]
> 数据栏没填任何数据

需要自己填写相对应的数据，参考“数据示例(使用时请删除注释)”

**Comment by poersche** [comment]
大佬，怎么添加数据啊

**Comment by poersche** [comment]
> 指的是 网站后台，节点管理 - 编辑 - 数据栏中的数据
我也出现了同样的问题，大佬能不能说的详细一点啊

**Comment by pingProMax** [comment]
> 大佬，怎么添加数据啊

这里
数据示例(使用时请删除注释)：
tcp:
协议:v2ray/vmess
{
  "port": "12345",
  "scy": "auto",
  "net": "tcp",
  "type": "none",
  "host": "",
  "path": "",
  "tls": "",
  "sni": "",
  "alpn": ""
}

**Comment by bestwishCT** [comment]
老哥你会添加数据了吗
