### ISSUE TITLE
openwrt的订阅链接怎么弄？

### ISSUE THREAD

**Issue by wisdomskip** [pingProMax/gov2panel#5]
openwrt上passwall的订阅链接怎么弄？

**Comment by pingProMax** [comment]
> openwrt上passwall的订阅链接怎么弄？

试试v2rayN的订阅地址

**Comment by wisdomskip** [comment]
试过了，不行

**Comment by pingProMax** [comment]
openwrt 你有可以用的订阅链接吗，发我看看

**Comment by xbclub** [comment]
> openwrt上passwall的订阅链接怎么弄？

亲测 shadowrocket的订阅链接在openwrt的passwall是可以使用的
