### ISSUE TITLE
邀请链接是否有设计？

### ISSUE THREAD

**Issue by pretty9527** [pingProMax/gov2panel#7]
表里有邀请码，邀请注册链接如何使用？另外后续有什么更新计划？

**Comment by pingProMax** [comment]
/register?code=xxx
自动填充邀请码

**Comment by pretty9527** [comment]
多谢，后续测试下。下一步有啥更新计划吗？

**Comment by pingProMax** [comment]
> 多谢，后续测试下。下一步有啥更新计划吗？

续费功能，修BUG，看看issues有没有什么好建议

**Comment by pretty9527** [comment]
> > 多谢，后续测试下。下一步有啥更新计划吗？
> 
> 续费功能，修BUG，看看issues有没有什么好建议
看以下功能如何配置
1.目前节点只能绑定一个订阅，是否能绑定多个？
2.是否可以按照用户等级，配置用户对应可以使用的节点？（目前和订阅绑定好像也没有什么问题）

**Comment by pingProMax** [comment]
> > > 多谢，后续测试下。下一步有啥更新计划吗？
> > 
> > 
> > 续费功能，修改BUG，看看问题有没有什么好建议
> > 看以下功能如何配置
> > 1.目前节点只能绑定一个订阅，是否能绑定多个？
> > 2.是否可以按照用户等级，配置用户对应可以使用（目前和订阅绑定希望也没有什么问题）

一个节点可用绑定多个订阅啊，节点设置“指定订阅”可用选择多个，
用户可用自行选择不同的订阅（节点绑定订阅）
